const types = {
  CLICK_BTN_A: 'CLICK_BTN_A',
  CLICK_BTN_B: 'CLICK_BTN_B',
  GET_NEW_PIC: 'GET_NEW_PIC',
  PRINT_PIC: 'PRINT_PIC',
  UPDATE_MESSAGE: 'UPDATE_MESSAGE',
  UPDATE_BUTTON_STATE:"UPDATE_BUTTON_STATE"
};

export default types;
